### ISSUE TITLE
Doesn't work with Python3

### ISSUE THREAD

**Issue by liverpoolfc-fan** [letsdebug/certbot-cpanel-dns-auth-hook#2]
Firstly, thank you for this script. I did get it working eventually. 

My server is running CentOS 8.1 and had Python3 as the default/only python installed. This threw up several errors in the script that I tried to work through (never having used python before). 

Eventually, I gave up, and installed Python2 side-by-side with Python3 for testing purposes 
yum install python2 python2-requests 
and changed the shebang to explicitly use /usr/bin/python2  In this environment it ran correctly first time. 

Please update the script to support Python3 or amend the documentation to call out the specific requirement for Python2 

Thanks

**Comment by alexzorin** [comment]
To be honest, I should not have posted this repo to begin with as it's never been in a particularly usable state of affairs. Can't recall why I did.

I've fixed up the Python 3 issues and added a (manually run) `tox` integration test to make sure that both `py27` and `py3` keep working into the future.
