### ISSUE TITLE
Add support for cpanel API token authorization

### ISSUE THREAD

**Issue by majurgens** [letsdebug/certbot-cpanel-dns-auth-hook#3]
Cpanel supports authorization by API token as per https://blog.cpanel.com/getting-started-with-the-cpanel-api/

Changing this code to support that would be as simple as being able to write the auth header as
`Authorization: cpanel $CPANEL_USER:$CPANEL_API_TOKEN # pseudo code showing output string format `

instead of how it is done at the moment: 
`Authorization: basic $CPANEL_USER $CPANEL_PASS # pseudo code showing output string format`

I guess you'd want to add support for this API token whilst also supporting the existing username/password as well.
This would need some, presumably simple python code to see if an API token was defined and then use that method if it was

**Comment by alexzorin** [comment]
Sure, sounds good.

Last time I looked I don't think API tokens were available for non-root users, but things seem to have progressed since then.

**Comment by majurgens** [comment]
Sorry, I would code it but I don't really know python that well.
